using System;
using System.Collections;
using System.Collections.Generic;
using Sirenix.OdinInspector;
using Sirenix.Serialization;
using UnityEngine;
using Object = System.Object;


namespace SparkleXRLib
{
    // One or more ControlsDescriptors to one GameInteractables
    // Surjective mapping from ControlsDescriptors to GameInteractables
    public abstract class ControlsDescriptor : SerializedMonoBehaviour
    {
        //TODO: Changes related with "SteamVR_Input Actions" feature
        //Something like: autogenerated list of actions i can assign Methods of Advanced method handling wrapper
        //One ControlsDescriptor to one XRNode. Whlie... that way)00)00

        public InputSourceType requiredInputSourceType { get; protected set; }
        public InputSourceVariant requiredInputSourceVariant { get; protected set; }

        public virtual void StartHandling(GameInteractor interactor) {}

        public virtual void StopHandling(GameInteractor interactor) {}
    }
}

